### ISSUE TITLE
hyperlink issue in README

### ISSUE THREAD

**Issue by tusharnankani** [PranavDani/Resume#2]
![image](https://user-images.githubusercontent.com/61280281/202426038-2903c3f0-7bd5-428d-b7d7-4387bc361647.png)

![image](https://user-images.githubusercontent.com/61280281/202425997-d09ae863-5591-4f6f-b1d3-05e92a52c593.png)

![image](https://user-images.githubusercontent.com/61280281/202426076-bb737390-0185-4e33-99ff-3dfeb419fe92.png)

Instead, write absolute path with https://

**Comment by PranavDani** [comment]
Fixed, thank you for pointing it out.
